name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Деплоим из ветки master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' 

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Check for changes and deploy
      run: |
        git config --global user.email "akylbekova.aizaada@gmail.com"
        git config --global user.name "Aizaada-Akylbek"
        
        # Проверяем, есть ли изменения, если есть, выполняем пуш
        git diff --exit-code || (
          echo "Changes detected, committing and pushing to master"
          git add -A
          git commit -m "Deploy to GitHub Pages"
          git push origin master
        )

    - name: Deploy to GitHub Pages
      run: npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.AIZAADA_TOKEN }}  # Используем твой токен
